default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: freelance_app_development

test:
  <<: *default
  database: freelance_app_test
  host: localhost
  username: postgres
  password: postgres

production:
  <<: *default
  database: freelance_app_production
  username: your_production_username
  password: <%= ENV['DATABASE_PASSWORD'] %>
