name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: windows-latest  # これを適切な環境に変更（例：windows-latest）

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6  # 統一されたRubyバージョン
          bundler-cache: true

      - name: Install brakeman
        run: gem install brakeman  # brakemanをインストール

      - name: Set executable permissions for bin/brakeman
        run: chmod +x bin/brakeman  # 必要なスクリプトにのみ権限を付与

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  scan_js:
    runs-on: windows-latest  # これを適切な環境に変更（例：windows-latest）

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6  # 統一されたRubyバージョン
          bundler-cache: true

      - name: Set executable permissions for bin/importmap
        run: chmod +x bin/importmap  # 必要なスクリプトにのみ権限を付与

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

  lint:
    runs-on: windows-latest  # これを適切な環境に変更（例：windows-latest）

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6  # 統一されたRubyバージョン
          bundler-cache: true

      - name: Set executable permissions for bin/rubocop
        run: chmod +x bin/rubocop  # 必要なスクリプトにのみ権限を付与

      - name: Lint code for consistent style
        run: bin/rubocop -f github
        
  test:
    runs-on: windows-2022  # Windowsランナーを指定

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PostgreSQL
        run: |
          choco install postgresql --params '/Password:postgres /Port:5432 /NoStackBuilder:true' -y
          setx /M PGUSER postgres
          setx /M PGPASSWORD postgres
          setx /M PGHOST localhost
          setx /M PGPORT 5432

      - name: Start PostgreSQL service
        shell: cmd
        run: |
         net start postgresql-x64-17 || echo "Service is already running, continuing..."

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Prepare test database
        run: bin/rails db:create

      - name: Prepare test database (db:test:prepare)
        run: bin/rails db:test:prepare

      - name: Run tests
        run: bin/rails test
